var Aluno = require('./Aluno')
var Professor = require('./Professor')
var Disciplina = require('./Disciplina')

disc1 = new Disciplina('Programacao OO', 64)
disc2 = new Disciplina('Estruturas de Dados', 96)
disc3 = new Disciplina('Banco de Dados', 64)

prof = new Professor('Joao', 'Av. BPS, 1303', 33, 'Doutorado', [])
prof.insereDisc(disc1)
prof.insereDisc(disc2)
prof.printDescricao()
console.log()
aluno = new Aluno('Pedro', 'Av. Cesario Alvin, 234', 20, 'SIN', [])
aluno.insereDisc(disc2)
aluno.insereDisc(disc3)
aluno.printDescricao()  
aluno.insereDisc(disc1) 
aluno.printDescricao() 